# Generated by Django 3.2.15 on 2022-12-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_auto_20221211_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Наличностью'), ('ELECTRIC', 'Электронно'), ('NO', 'Не указан')], db_index=True, default='NO', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
