# Generated by Django 3.2.15 on 2022-12-11 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_alter_order_restaurant_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='restaurant_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='foodcartapp.restaurant', verbose_name='Ресторан, который готовит заказ'),
        ),
    ]
