# Generated by Django 3.2.15 on 2022-12-12 19:06

from django.db import migrations


def copy_new_price(apps, schema_editor):
    Product = apps.get_model('foodcartapp', 'Product')
    ProductQuantity = apps.get_model('foodcartapp', 'ProductQuantity')
    products = Product.objects.all()
    for product in products.iterator():
        products_quantity = product.product_quantity.all()
        for product_quantity in products_quantity:
            product_quantity.price = product.price
        ProductQuantity.objects.bulk_update(products_quantity, ['price'])


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_alter_order_restaurant_order'),
    ]

    operations = [
        migrations.RunPython(copy_new_price)
    ]