# Generated by Django 3.2.15 on 2022-12-22 14:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_auto_20221214_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productquantity',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество продукта'),
        ),
    ]
