# Generated by Django 3.2.15 on 2022-12-22 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0058_auto_20221222_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='restaurant_order',
            new_name='selected_restaurant',
        ),
    ]
